version: '3.5'

services:
  opcsback:
    image: opcsback
    container_name: OPCSBack
    build: 
      context: .
      dockerfile: Dockerfile.back
    volumes: 
      - ./sqlite3:/app/sqlite3
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 10002:9999
  opcsfront:
    image: opcsfront
    container_name: OPCSfront
    build: 
      context: .
      dockerfile: Dockerfile.front
    ports:
      - 10001:8080
