version: 2
jobs:
  build1:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run:
          name: Building Dist
          command: npm run build
      - save_cache:
          key: OCPS-{{ .Environment.CIRCLE_SHA1 }} 
          paths:
            - ~/opcs-workflows
