version: 2
jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run: 
          command: |
            npm install
            npm run build
            ln -s ./dist/ /var/www/